name: Generate Tests via GHCR

on:
  push:
    branches: [main]

permissions:
  contents: write
  packages: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull & Run Test Generator from GHCR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker run --rm -e GITHUB_TOKEN=$GITHUB_TOKEN ghcr.io/itamarzand88/test-generator:latest
